executive/executives/executives/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('', include('mainapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('laureladmin/', admin.site.urls),

]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

executive/executives/mainapp/urls.py
from django.urls import path
from .views import (
  evaluation_form,
  directorate_form,
  executives_page,
  application_submit
)

app_name = "mainapp"
urlpatterns = [
    path('', executives_page, name="executives_page"),
    path('evaluation/', evaluation_form, name="evaluation_form"),
    path('directorate/', directorate_form, name="directorate_form"),
    path('application-submit/', application_submit, name="application_submit"),
]

executive/executives/mainapp/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Evaluation(models.Model):
  name = models.CharField( max_length=100) 
  directorate  = models.CharField( max_length=100) 
  job  = models.CharField("Job performed this month", max_length=400) 
  reasons  = models.CharField("Reason, if no job performed", max_length=400) 
  attendance  = models.CharField("Attendance at monthly meeting ", max_length=400) 
  absent  = models.CharField("Reason, if absent", max_length=400) 
  date = models.DateField(auto_now=True, auto_now_add=False)

  class Meta:
    verbose_name = "KLA Monthly Members and Executives Evaluation Sheet"
    verbose_name_plural = "KLA Monthly Members and Executives Evaluation Sheet"

  def __str__(self):
      return self.name
  


class Directorate(models.Model):
  name = models.CharField( max_length=100) 
  plans_for_the_quarter = models.TextField()
  resources_needed = models.TextField()
  challenges_faced_in_the_previous_quarter = models.TextField()
  how_the_challenges_can_be_addressed = models.TextField()


  class Meta:
    verbose_name = "Directorate's Quarterly Evaluation Form"
    verbose_name_plural = "Directorate's Quarterly Evaluation Form"

  def __str__(self):
      return self.name

class Contact(models.Model):
  name = models.CharField("", max_length=100)
  email = models.EmailField("", max_length=254)
  subject = models.CharField("", max_length=500)
  message = models.TextField("")

  class Meta:
    verbose_name = 'Contact'
    verbose_name_plural = 'Contacts'

  def __str__(self):
    return self.name
  

executive/executives/mainapp/forms.py
from django import forms
from .models import *


class EvaluationForm(forms.ModelForm):
    class Meta:
        model = Evaluation
        fields = "__all__"


class DirectorateForm(forms.ModelForm):
    class Meta:
        model = Directorate
        fields = "__all__"


from django import forms
from .models import Contact



class ContactForm(forms.ModelForm):
  name = forms.CharField(label='', max_length=250, required=True, widget=forms.TextInput(attrs={
        'placeholder':"Name",
        "class": "form-item"

    }))
  subject = forms.CharField(label='', max_length=250, required=False, widget=forms.TextInput(attrs={
        'placeholder':"Subject",
        "class": "form-item"

    }))
  email = forms.EmailField(label='', widget=forms.EmailInput(attrs={
        'placeholder':"Email Address",
        "class": "form-item"
    }))
  message = forms.CharField(label='', widget=forms.Textarea(attrs={
        'placeholder': "Write your message here",
        'rows': 3,
        "class": "form-item"

    }))

  class Meta:
    model = Contact
    fields = ["name", "email", "subject", "message"]

executive/executives/mainapp/views.py
from django.shortcuts import render, redirect
from .forms import EvaluationForm, DirectorateForm
from django.contrib import messages





def executives_page(request):

  return render(request, "mainapp/executives_page.html")


def evaluation_form(request):
  if request.method == 'POST':
    form = EvaluationForm(request.POST)
    if form.is_valid():
      form.save()
      messages.info(request, 'Your form has been submitted successfully.')
      return redirect('mainapp:application_submit')

  
  form = EvaluationForm()


  context = {
    "form" : form
  }
  return render(request, "mainapp/evaluation_form.html", context)


def directorate_form(request):
  if request.method == 'POST':
    form = DirectorateForm(request.POST)
    if form.is_valid():
      form.save()
      messages.info(request, 'Your form has been submitted successfully.')
      return redirect('mainapp:application_submit')

  
  form = DirectorateForm()


  context = {
    "form" : form
  }
  return render(request, "mainapp/directorate_form.html", context)


def application_submit(request):
  
  return render(request, 'mainapp/application_submit.html')

executive/executives/mainapp/templates/mainapp/application_submit.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
  <section class="section form-center">
    <div class="section-head">
      <h3>Your form has been submitted successfully.</h3>
      <br>
      <a href="https://www.kingdomleadsafrica.org" class="signup-url"><p>click Return to Home page</p></a>
      <div class="section-underline"></div>
    </div>
      <br>
      </div>
  </section>

{% endblock content %}

executive/executives/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Kingdom Leads Africa Executives Page</title>
  <link rel="stylesheet" href="{% static 'mainapp/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'mainapp/fontawesome-free-5.7.2-web 2/css/all.css' %}">
  <link rel="stylesheet" href="{% static 'mainapp/css/owlcarousel/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'mainapp/css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'mainapp/css/magnific-popup.css' %}">
</head>
<body>
  {% include "mainapp/nav.html" %}
  {% if messages %} 
    {% for message in messages %}
    <div class="section form-center">
      <p class="messages-{{message.tags}}">
      {{ message }}</p>
    </div>
        {% endfor %} 
        {% endif %} 
  {% block content %}
  
  {% endblock content %}
  {% include "mainapp/footer.html" %}
  
  <script src="{% static 'mainapp/js/scripts.js' %}"></script>
  <script src="{% static 'mainapp/js/googlejquery.js' %}"></script>
  <script src="{% static 'mainapp/js/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'mainapp/js/owlcarousel/owl.autoplay.js' %}"></script>
  <script src="{% static 'mainapp/js/aos.js' %}"></script>
  <script src="{% static 'mainapp/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'mainapp/js/utility.js' %}"></script>
  <script src="{% static 'mainapp/js/magnific.js' %}"></script>
  <script>
    AOS.init()
  </script>
</body>
</html>

executive/executives/mainapp/templates/mainapp/contact.html
{% load static %}
    <form action="." method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <button><i class="fas fa-envelope"></i> send message</button>
      </form>

executive/executives/mainapp/templates/mainapp/directorate_form.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
  <section class="section form-center">
    <div class="section-head">
      <h3>DIRECTORATE'S QUARTERLY EVALUATION FORM</h3>
      <div class="section-underline"></div>
    </div>
    <p>To be filled every three month. </p>
      <br>
      <div class="form-container">
        <form action="." method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="form-btn">Submit</button>
        </form>
      </div>
  </section>

{% endblock content %}

executive/executives/mainapp/templates/mainapp/evaluation_form.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
  <section class="section form-center">
    <div class="section-head">
      <h3>KLA Monthly Members and Executives Evaluation Form </h3>
      <div class="section-underline"></div>
    </div>
      <br>
      <div class="form-container">
        <form action="." method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="form-btn">Submit</button>
        </form>
      </div>
  </section>

{% endblock content %}

executive/executives/mainapp/templates/mainapp/executives_page.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
  <section class="section form-center">
    <div class="section-head">
      <h3>ORGANOGRAM</h3>
      <div class="section-underline"></div>
    </div>
      <br>
      <h4>BOARD OF TRUSTEES</h4>
      <div class="form-container blog-detail">
        <ul>
          <li>This is the highest decision-making body of the organisation </li>
          <li>Takes administrative decisions for the organisation </li>
          <li>Gives ultimate sanction for every misconduct or negligence within the organisation </li>
          <li>Members and executives can submit an appeal to the BoT if they have any concerns about anything and anyone within the organisation </li>
        </ul>
      </div>
      <br>
      <h4>EXECUTIVES</h4>
      <div class="form-container blog-detail">
        <ul>
          <li>The executive position is for a year (January to December) after which the executive can decide whether to continue or to hand over.</li>
          <li>Every executive must take full responsibility for his/her members </li>
          <li>Negligence of duty without appropriate permission will attract penalties as determined by the Board of Trustees  </li>
        </ul>
      </div>
    
    
    <div class="section-head">
      <h3>ROLE DESCRIPTION </h3>
      <div class="section-underline"></div>
    </div>
      <br>
      <h4>KLI BOARD OF TRUSTEES </h4>
      <div class="form-container blog-detail">
        <ul>
          <li>President </li>
          <li>Vice President </li>
          <li>General Secretary </li>
          <li>Human Resources director</li>
        </ul>
      </div>
      <br>
      <h4>KLI EXECUTIVE POSITIONS</h4>
      <div class="form-container blog-detail">
        <ul>
          <li>President</li>
          <li>Vice President</li>
          <li>General Secretary</li>
          <li>Content Directorate </li>
          <li>Publicity Directorate </li>
          <li>Editorial Directorate </li>
          <li>Grants Directorate </li>
          <li>Finance Directorate </li>
          <li>Special Duty Directorate </li>
          <li>Human Resources Directorate </li>
          <li>Design & Videography Directorate </li>
        </ul>
      </div>
      <br>
      <h4>ROLES OF EXECUTIVES</h4>
      <div class="form-container blog-detail">
      <h5>President/Team Lead (TL)</h5>
        <ul>
          <li>The overall head of the organization</li>
          <li>Ensures that the other executives work in line with the organization's goal and vision </li>
        </ul>
        <br>
      <h5>Vice President </h5>
        <ul>
          <li>To assist the President in the supervisory role</li>
          <li>Can act on behalf of the President once he/she has the directive to do so </li>
        </ul>
        <br>
      <h5>General Secretary (GS) </h5>
        <ul>
          <li>Keeps important documents of the organization electronically </li>
          <li>Write the briefs of every meeting and store them electronically  </li>
          <li>Submit monthly summary to the president on achievements and limitations  </li>
        </ul>
        <br>
      <h5>Content Directorate(CD)</h5>
        <ul>
          <li>Create the content for every graphic, clip, bulletin, seminar, summit, conference, social impact project etc of the organization </li>
          <li>Work closely with other executives to generate content  </li>
          <li>All contents must go through the Editorial directorate for proper review and correction.  </li>
          <li>Submit monthly summary to the president on directorate achievements and limitations </li>
        </ul>
        <br>
      <h5>Design and videography Directorate (DVD) </h5>
        <ul>
          <li>Should have graphic designers and videography </li>
          <li>Transform the content into graphic designs and/or video clips </li>
          <li>Submit monthly summary to the president on directorate achievements and limitations</li>
        </ul>
        <br>
      <h5>Editorial Directorate(ED)</h5>
        <ul>
          <li>Review every document or content created by the General secretary, content directorate and DVD for correctness before they are stored or published.</li>
          <li>Submit monthly summary to the president on directorate achievements and limitations </li>
        </ul>
        <br>
      <h5>Publicity Directorate (PD) </h5>
        <ul>
          <li>Publication and dissemination of graphics, bulletins, clips, tweets and posts etc </li>
          <li>Manages the social media handles of the organization ( Instagram, Twitter, Facebook, LinkedIn, youtube) </li>
          <li>Manages the website of the organization for updating events, activities and other contents</li>
          <li>Submit monthly summary to the president on directorate achievements and limitations</li>
        </ul>
        <br>
      <h5>Grants Directorate(GD) </h5>
        <ul>
          <li>Search for available grants to fund the various projects and programs of the organization  </li>
          <li>Work with the general secretary and editorial directors in applying for the grants</li>
          <li>Follow up on grants applied for and periodically look for other grants </li>
          <li>Win grants for the organization </li>
          <li>Submit monthly summary to the president on directorate achievements and limitations</li>
        </ul>
        <br>
      <h5>Finance Directorate (FD)</h5>
        <ul>
          <li>Keep a record of the organization income and expenditures </li>
          <li>Source for funds (aside from grants) to finance various projects and programs of the organization.</li>
          <li>Be in charge of monthly contributions from members</li>
          <li>Submit monthly summary to the president on directorate achievements and limitations</li>
        </ul>
        <br>
      <h5>Special Duty Directorate (SDD)</h5>
        <ul>
          <li>Manages the distribution of letters </li>
          <li>Sets up the venue of events</li>
          <li>Work with the president and general secretary to meet with partners.</li>
          <li>Performs other activities that are not in the jurisdiction of any directorate </li>
          <li>Submit monthly summary to the president on directorate achievements and limitations</li>
        </ul>
        <br>
      <h5>Human Resources Directorate (HRD)</h5>
        <ul>
          <li>Ensure the welfare of every executive and member of the organization</li>
          <li>Recruit and train new members for the organization </li>
          <li>Ensure regular and periodic training of executives and members of the organization on various things like our values, leadership, soft skills, hard skills and other life-transforming seminars </li>
          <li>Ensure refreshments for every event or meeting.</li>
          <li>Submit monthly summary to the president on directorate achievements and limitations </li>
        </ul>
        <br>
      </div>
      <div class="section-head">
      <h3>ORGANIZATIONAL EVENTS AND FLOW CHART</h3>
      <div class="section-underline"></div>
    </div>
      <br>
      <h4>RECURRENT EVENTS</h4>
      <div class="form-container blog-detail">
        <ol>
          <li>Leadership/SDG Tweet(graphic)…. <b>Weekly (sundays)</b></li>
          <li>Short leadership charge clip… <b>Monthly (1st Tuesdays )</b> </li>
          <li>Roleplay on/ Dramatization of leadership qualities…. <b>Bimonthly ( 1st Fridays)</b></li>
          <li>Bulletin on Leadership/SDG (1-2 pages)… <b>Quarterly (1st Mondays)</b></li>
          <li>In-house training (value exposition, soft & hard skill training, book review, SDG exposition etc) … <b>During monthly meetings</b> </li>
          <li><b>Annual</b> Leadership summit with SDG events (Tertiary category) </li>
          <li><b>Annual</b> Leadership summit with SDG events (High school category)</li>
          <li>Book writing and launching </li>
        </ol>
      </div>
      <br>
      <h4>FLOW CHART FOR EVENTS</h4>
      <div class="form-container blog-detail flow-chart">
        <ol>
          <li><b>Weekly quote(graphic): </b>CD <i class="fas fa-arrow-right"></i> ED <i class="fas fa-arrow-right"></i> CD <i class="fas fa-arrow-right"></i> DVD <i class="fas fa-arrow-right"></i> TL <i class="fas fa-arrow-right"></i> GS <i class="fas fa-arrow-right"></i> PD <i class="fas fa-arrow-right"></i> Public</li>
          <li><b>Short leadership charge clip: </b> CD <i class="fas fa-arrow-right"></i> ED <i class="fas fa-arrow-right"></i> CD <i class="fas fa-arrow-right"></i> SDD <i class="fas fa-arrow-right"></i> CD <i class="fas fa-arrow-right"></i> DVD <i class="fas fa-arrow-right"></i> TL <i class="fas fa-arrow-right"></i> GS <i class="fas fa-arrow-right"></i> PD <i class="fas fa-arrow-right"></i> Public</li>
          <li><b>Roleplay on/ Dramatization of leadership qualities:  </b> CD <i class="fas fa-arrow-right"></i> ED <i class="fas fa-arrow-right"></i> CD <i class="fas fa-arrow-right"></i> SDD <i class="fas fa-arrow-right"></i> CD <i class="fas fa-arrow-right"></i> DVD <i class="fas fa-arrow-right"></i> TL <i class="fas fa-arrow-right"></i> GS <i class="fas fa-arrow-right"></i> PD <i class="fas fa-arrow-right"></i> Public</li>
          <li><b>Bulletin on Leadership (1-2 pages):  </b> CD <i class="fas fa-arrow-right"></i> ED <i class="fas fa-arrow-right"></i> CD <i class="fas fa-arrow-right"></i> DVD <i class="fas fa-arrow-right"></i> TL <i class="fas fa-arrow-right"></i> GS <i class="fas fa-arrow-right"></i> PD <i class="fas fa-arrow-right"></i> Public</li>
          <li><b>In-house training (value exposition, soft & hard skill training, book review, SDG exposition etc):  </b>HRD <i class="fas fa-arrow-right"></i> ED <i class="fas fa-arrow-right"></i> HRD <i class="fas fa-arrow-right"></i> SDD <i class="fas fa-arrow-right"></i> HRD <i class="fas fa-arrow-right"></i> DVD <i class="fas fa-arrow-right"></i> HRD <i class="fas fa-arrow-right"></i> TL <i class="fas fa-arrow-right"></i> GS <i class="fas fa-arrow-right"></i> HRD</li>
          <li><b>Annual Leadership summits (Tertiary category):  </b>SDD, HRD, CD, TL & GS <i class="fas fa-arrow-right"></i> GD & FD <i class="fas fa-arrow-right"></i> SDD, HRD, CD, TL & GS <i class="fas fa-arrow-right"></i> ED <i class="fas fa-arrow-right"></i> SDD, HRD, CD, TL & GS <i class="fas fa-arrow-right"></i> DVD <i class="fas fa-arrow-right"></i> DVD <i class="fas fa-arrow-right"></i> SDD, HRD, CD, TL & GS <i class="fas fa-arrow-right"></i> PD <i class="fas fa-arrow-right"></i> Public</li>
          <li><b>Annual Leadership summits (High school category):  </b>SDD, HRD, CD, TL & GS <i class="fas fa-arrow-right"></i> GD & FD <i class="fas fa-arrow-right"></i> SDD, HRD, CD, TL & GS <i class="fas fa-arrow-right"></i> ED <i class="fas fa-arrow-right"></i> SDD, HRD, CD, TL & GS <i class="fas fa-arrow-right"></i> DVD <i class="fas fa-arrow-right"></i> DVD <i class="fas fa-arrow-right"></i> SDD, HRD, CD, TL & GS <i class="fas fa-arrow-right"></i> PD <i class="fas fa-arrow-right"></i> Public</li>
        </ol>
      </div>

<div class="section-head">
      <h3>LONG TERM PLANS</h3>
      <div class="section-underline"></div>
    </div>
      <br>
      <h4>5 YEAR PLAN:  LAYING A SOLID & SELF SUSTAINING FOUNDATION </h4>
      <div class="form-container blog-detail">
        <ol>
          <li>To have well motivated members and Executives</li>
          <li>To publish an attractive age appropriate fellowship coursework for both high school and tertiary categories</li>
          <li>To develop the most effective way to recruit, deliver and coordinate the fellowship (virtual &/or physical)</li>
          <li>To develop organisation website that will also contain the portal for the fellowship </li>
          <li>To develop a concise and motivating proposal for potential donors and sponsors for the fellowship </li>
          <li>To register the organisation as corporate body</li>
          <li>To create the bank account for the organisation (local & domiciliary)</li>
          <li>To develop a student friendly mobile app that will serve as a tool for having a seamless fellowship experience </li>
          <li>Successfully organize and execute at least 2 fellowships in both tertiary and secondary categories </li>
        </ol>
      </div>
      <br>
      <h4>10 YEARS PLAN: BUILD SUPERSTRUCTURE ON THE SOLID FOUNDATION </h4>
      <div class="form-container blog-detail">
        <ul>
          <li>Extend the tentacle of the fellowship </li>
          <li>Review the foundation and make it better</li>
          <li>Strengthen the mentorship scheme </li>
          <li>Develop the social enterprise component of the organisation </li>
          <li>Review the coursework and publish it with better graphics  </li>
        </ul>
      </div>
      <div class="form-container">
        <p><a href="{% url 'mainapp:directorate_form' %}" class="signup-url">Click here to fill directorate's evaluation form.</a></p>
        <p><a href="{% url 'mainapp:evaluation_form' %}" class="signup-url">Click here to fill KLA Monthly Members and Executives Evaluation Form</a></p>
      </div>
      <br>
      <br>
  </section>

{% endblock content %}

executive/executives/mainapp/templates/mainapp/footer.html
{% load klatags %}
  <footer class="footer">
    <article class="footer-items">
      <div class="footer-contact">
        <div class="contact-us">
          <div class="footer-head">
            <h3>contact us</h3>
            <div class="footer-underline"></div>
          </div>
          <div class="contact-item">
            <i class="fas fa-address-book"></i>
            <p>E44, Alexander Brown Hall, Ibadan</p> 
          </div>
          <div class="contact-item">
            <i class="fas fa-phone"></i> 
            <p>+2348163482948</p>
          </div>
          <div class="contact-item">
            <i class="fas fa-envelope"></i>
            <a href="mailto:kingdomleads2021@gmail.com">kingdomleads2021@gmail.com</a>
          </div>
        </div>
        <div class="contact-form">
          {% contact_tag request %}
        </div>
        <div class="footer-menu">
          <div class="footer-head">
            <h3>Navigate the Site</h3>
            <div class="footer-underline"></div>
          </div>
          <ul class="footer-links">
          <li><a href="https://www.kingdomleadsafrica.org">home</a></li>
          <li><a href="https://www.kingdomleadsafrica.org/about-us">about us</a></li>
          <li><a href="https://www.kingdomleadsafrica.org/our-executives">meet the executives</a></li>
          <li><a href="https://www.kingdomleadsafrica.org/programs">our programs</a></li>
          <li><a href="https://www.kingdomleadsafrica.org/membership">become a member</a></li>
          <li><a href="https://www.kingdomleadsafrica.org/donation">donation/partnership</a></li>
          <li><a href="https://www.kingdomleadsafrica.org/blog">blog</a></li>
        </ul>
        </div>
      </div>
    </article>

    <article class="footer-note">
      <div class="footer-icons">
          <div class="footer-icon">
            <a href="https://www.facebook.com/100076501002706"><i class="fab fa-facebook"></i></a>
          </div>
          <div class="footer-icon">
            <a href="https://twitter.com/kingdomleads"><i class="fab fa-twitter"></i></a>
          </div>
          <div class="footer-icon">
            <a href="https://www.instagram.com/kingdomleadsafrica"><i class="fab fa-instagram"></i></a>
          </div>
        </div>
        <div class="footer-right">
          <p>&copy; <span class="footer-date"></span> Kingdom Leads Africa. all right reserved</p>
        </div>
        <div class="designer">
          <p>site designed by <a href="https://twitter.com/Odeniyiojo">Heritage web dev</a></p>
        </div>
    </article>
  </footer>

executive/executives/mainapp/templates/mainapp/nav.html
{% load static %}
{% url 'main:home_page' as home %}
{% url 'main:our_executives' as executives %}
{% url 'main:about_page' as about %}
{% url 'main:programs_page' as programs %}
{% url 'main:donation_page' as donation %}
{% url 'membership:application_form' as membership %}
{% url 'blog:post_list' as blog %}
<header>
    <nav class="nav-bar">
      <div class="nav-top">
        <div class="nav-logo">
          <a href="https://www.kingdomleadsafrica.org">
            <img src="{% static 'mainapp/img/logo.png' %}" alt="my logo">
          </a>
        </div>
        <div class="nav-btn">
          <i class="fas fa-bars"></i>
        </div>
      </div>
      <div class="nav-contents">
        <ul class="nav-links">
          <li class="{% if request.path == home %} active-nav {% endif %}"><a href="https://www.kingdomleadsafrica.org" class="nav-link">home</a></li>
          <li class="{% if request.path == about %} active-nav {% endif %}"><a href="https://www.kingdomleadsafrica.org/about-us" class="nav-link">about us</a></li>
          <li class="{% if request.path == executives %} active-nav {% endif %}"><a href="https://www.kingdomleadsafrica.org/our-executives" class="nav-link">meet the executives</a></li>
          <li class="{% if request.path == programs %} active-nav {% endif %}"><a href="https://www.kingdomleadsafrica.org/programs" class="nav-link">our programs</a></li>
          <li class="{% if request.path == membership %} active-nav {% endif %}"><a href="https://www.kingdomleadsafrica.org/membership" class="nav-link">become a member</a></li>
          <li class="{% if request.path == donation %} active-nav {% endif %}"><a href="https://www.kingdomleadsafrica.org/donation" class="nav-link">donation/partnership</a></li>
          <li class="{% if request.path == blog %} active-nav {% endif %}"><a href="https://www.kingdomleadsafrica.org/blog" class="nav-link">blog</a></li>
            {% comment %} {% if user.is_authenticated %}
          <li><a href="{% url 'account_logout' %}" class="nav-link">logout</a></li>
          {% else %}
          <li><a href="{% url 'account_login' %}" class="nav-link">login</a></li>
          {% endif %} {% endcomment %}
          {% comment %} <li><a href="{% url 'main:home_page' %}" class="nav-link">home</a></li>
          <li><a href="{% url 'main:about_page' %}" class="nav-link">about us</a></li>
          <li><a href="{% url 'main:our_executives' %}" class="nav-link">meet the executives</a></li>
          <li><a href="{% url 'main:programs_page' %}" class="nav-link">our programs</a></li>
          <li><a href="{% url 'membership:application_form' %}" class="nav-link">become a member</a></li>
          <li><a href="{% url 'main:donation_page' %}" class="nav-link">donation/partnership</a></li>
          <li><a href="{% url 'blog:post_list' %}" class="nav-link">blog</a></li>
            {% if user.is_authenticated %}
          <li><a href="{% url 'account_logout' %}" class="nav-link">logout</a></li>
          {% else %}
          <li><a href="{% url 'account_login' %}" class="nav-link">login</a></li>
          {% endif %} {% endcomment %}

        </ul>
      </div>
    </nav>
  </header>