mainsite/src/blog/urls.py
from django.urls import path
from .views import (
    post_list,
    post_detail
)

app_name = 'blog'
urlpatterns = [
    path('', post_list, name="post_list"),
    path('<int:pk>/<str:slug>/', post_detail, name="post_detail"),
]

mainsite/src/kli/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls')),
    path('membership/', include('membership.urls')),
    path('accounts/', include('allauth.urls')),
    path('laureladmin/', admin.site.urls)
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainsite/src/main/urls.py
from django.urls import path
# from material.admin.sites import site
from .views import (
    home_page,
    about_page,
    donation_page,
    our_executives,
    programs_page
    )

app_name = "main"
urlpatterns = [
    path('', home_page, name="home_page"),
    path('about-us/', about_page, name="about_page"),
    path('donation/', donation_page, name="donation_page"),
    path('our-executives/', our_executives, name="our_executives"),
    path('programs/', programs_page, name="programs_page"),
]

mainsite/src/membership/urls.py
from django.urls import path
# from material.admin.sites import site
from .views import (
    application_form,
    application_submit
    )

app_name = "membership"
urlpatterns = [
    path('', application_form, name="application_form"),
    path('submit/', application_submit, name="application_submit"),
]

mainsite/src/main/models.py
from django.db import models
from django.contrib.auth.models import User

class Event(models.Model):
  title = models.CharField(max_length=100)
  date = models.DateField(auto_now=False, auto_now_add=False)
  details = models.CharField(max_length=500)
  author = author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
  image = models.ImageField( upload_to="event-image")

  class Meta:
    verbose_name = 'Event'
    verbose_name_plural = 'Events'

  def __str__(self):
    return self.title


class Contact(models.Model):
  name = models.CharField("", max_length=100)
  email = models.EmailField("", max_length=254)
  subject = models.CharField("", max_length=500)
  message = models.TextField("")

  class Meta:
    verbose_name = 'Contact'
    verbose_name_plural = 'Contacts'

  def __str__(self):
    return self.name

mainsite/src/main/forms.py
from django import forms
from .models import Contact



class ContactForm(forms.ModelForm):
  name = forms.CharField(label='', max_length=250, required=True, widget=forms.TextInput(attrs={
        'placeholder':"Name",
        "class": "form-item"

    }))
  subject = forms.CharField(label='', max_length=250, required=False, widget=forms.TextInput(attrs={
        'placeholder':"Subject",
        "class": "form-item"

    }))
  email = forms.EmailField(label='', widget=forms.EmailInput(attrs={
        'placeholder':"Email Address",
        "class": "form-item"
    }))
  message = forms.CharField(label='', widget=forms.Textarea(attrs={
        'placeholder': "Write your message here",
        'rows': 3,
        "class": "form-item"

    }))

  class Meta:
    model = Contact
    fields = ["name", "email", "subject", "message"]

mainsite/src/main/views.py
from django.shortcuts import render
from blog.models import Post
from .models import Event

# Create your views here.

def home_page(request):
  posts = Post.objects.all().order_by("-id")[:3]
  events = Event.objects.all().order_by("-id")[:3]
  
  context = {
    "posts" : posts,
    "events" : events
  }
  return render(request, 'main/index.html', context)


def about_page(request):
  
  return render(request, 'main/about.html')


def donation_page(request):
  
  return render(request, 'main/donation.html')


def our_executives(request):
  
  return render(request, 'main/executives.html')


def programs_page(request):
  
  return render(request, 'main/programs.html')

mainsite/src/main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <section class="about-page">
    <div class="section-head">
      <h1>About Us</h1>
      <div class="section-underline"></div>
    </div>
      <br>
      <p>KLA, a pro leadership non profit organization that is founded to equip high school leavers and fresh students of tertiary institutions with true leadership skills through her various life changing conferences, summits, fellowships and SDG oriented social impact projects.</p>
    <div class="about-center">
        <article class="about-img" data-aos="fade-right" data-aos-duration="2000">
          <img src="{% static 'main/img/images (5).png' %}" alt="" />
        </article>
        <article class="about">
          <!-- btn container -->
          <div class="btn-container">
            <button class="tab-btn active" data-id="vision">vision</button>
            <button class="tab-btn" data-id="mission">mission</button>
            <button class="tab-btn" data-id="values">values</button>
          </div>
          <div class="about-content">
            <!-- single item --> 
            <div class="content active" id="vision">
              <h4>vision</h4>
              <p>
                To be the foremost international, pro leadership and non-profit organisation that transforms African youths into true leaders.
              </p>
            </div>
            <!-- end of single item -->
            <!-- single item -->
            <div class="content" id="mission">
              <h4>mission</h4>
              <ul>
                <li>To admit fresh tertiary students as fellows of the Freshire Campus Fellowship every yea</li>
                <li>To admit senior secondary/high school students as fellows of the Highsphire Network of Promising Leaders every year</li>
                <li>To provide lifetime mentorship in all aspects of life for every HNPL and FCF fellows.</li>
                <li>To make leaders relevant throughout their lifetime by providing mentorship to younger leaders</li>
                <li>To positively impact the world via problem solving innovations and societal-improvement fellowship projects executed by fellows</li>
                <li>Ultimately, to develop and coach leaders that will respond effectively to political, business, spiritual, financial and educational problems of their families, communities and nations.</li>
              </ul>
            </div>
            <!-- end of single item -->
            <!-- single item -->
            <div class="content" id="values">
              <h4>values</h4>
              <ul>
                <li>Absolute faith in God </li>
                <li>Genuine love for People</li>
                <li>Deep selflessness</li>
                <li>Complete self mastery </li>
                <li>Exceptional knowledge & wisdom </li>
                <li>Excellent creativity & Innovation</li>
                <li>Clear vision </li>
                <li>Outstanding Courage</li>
                <li>Great ability to Influence</li>
                <li>Premium value on relationships</li>
                <li>Effective Communication</li>
                <li>Great sense of timeliness</li>
              </ul>
            </div>
            <!-- end of single item -->
          </div>
        </article>
      </div>
  </section>
{% endblock content %}

mainsite/src/main/templates/main/banner.html
{% load static %}
<section class="banner">
      <div class="banner-video">
        <video muted autoplay loop class="video-container">
        <source src="{% static 'main/img/banner small.mp4' %}" type="video/mp4" />
      </video>
        <!-- <img src="./img/IMG_0102.HEIC" alt="">
        <img src="./img/vision-2372177.jpg" alt="">
        <img src="./img/IMG_0003.JPG" alt=""> -->
      </div>
      <div class="banner-text">
        <h1>Kingdom Leads</h1>
        <h3>Africa</h3>
        <br>
        <p>Promoting the lifestyle of true leadership in Africa</p>
      </div>
      <!-- <div class="banner-text">
        <p>Banner will be here</p>
      </div> -->
    </section>

mainsite/src/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Kingdom Leads Africa</title>
  <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'main/fontawesome-free-5.7.2-web 2/css/all.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/owlcarousel/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/magnific-popup.css' %}">
</head>
<body>
  {% include "main/nav.html" %}
  {% if messages %} 
    {% for message in messages %}
    <div class="section form-center">
      <p class="messages-{{message.tags}}">
      {{ message }}</p>
    </div>
        {% endfor %} 
        {% endif %} 
  {% block content %}
  
  {% endblock content %}
  {% include "main/footer.html" %}
  
  <script src="{% static 'main/js/scripts.js' %}"></script>
  <script src="{% static 'main/js/googlejquery.js' %}"></script>
  <script src="{% static 'main/js/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'main/js/owlcarousel/owl.autoplay.js' %}"></script>
  <script src="{% static 'main/js/aos.js' %}"></script>
  <script src="{% static 'main/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'main/js/utility.js' %}"></script>
  <script src="{% static 'main/js/magnific.js' %}"></script>
  <script>
    AOS.init()
  </script>
</body>
</html>

mainsite/src/main/templates/main/contact.html
{% load static %}
    <form action="." method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <button><i class="fas fa-envelope"></i> send message</button>
      </form>

mainsite/src/main/templates/main/donation.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <section class="section">
    <div class="section-head">
      <h3>Do you want to donate or partner with us? you can contact us via:</h3>
      <div class="section-underline"></div>
    </div>
    
  </section>
{% endblock content %}

mainsite/src/main/templates/main/executives.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
  <section class="executives">
    <div class="executives-head">
          <h1>meet our executives</h1>
          <div class="executives-underline"></div>
      </div>
    <div class="executives-center">
      <!-- single executive -->
      <article class="executive" data-aos="fade-up" data-aos-duration="2000">
        <div class="executive-img-container">
          <img src="{% static 'main/img/kolawole.jpg' %}" alt="">
        </div>
        <div class="executive-info">
          <h2 class="name">Kolawole olanrewaju</h2>
          <h3 class="position">team lead</h3>
          <p class="detail">600L, Medicine and Surgery UI. Fellow, YALI & MCN, </p>
          <p class="quote">"We are our raw material, we are our finished product, leadership is the process of the transformation "</p>
        </div>
      </article>
      <!-- end of single executive -->
      <!-- single executive -->
      <article class="executive" data-aos="fade-up" data-aos-duration="2000">
        <div class="executive-img-container">
          <img src="{% static 'main/img/Odekunle mercy.jpg' %}" alt="">
        </div>
        <div class="executive-info">
          <h2 class="name">Odekunle Mercy </h2>
          <h3 class="position">General secretary</h3>
          <p class="detail">Graduate of Health Education, UI</p>
          <p class="quote">"True leadership cannot be divorced from the basic qualities that produce good and sound characters"</p>
        </div>
      </article>
      <!-- end of single executive -->
      <!-- single executive -->
      <article class="executive" data-aos="fade-down" data-aos-duration="2000">
        <div class="executive-img-container">
          <img src="{% static 'main/img/abe oluwatoyin.jpg' %}" alt="">
        </div>
        <div class="executive-info">
          <h2 class="name">Abe Oluwatoyin</h2>
          <h3 class="position">Financial director </h3>
          <p class="detail">Graduate of Biochemistry, UI </p>
          <p class="quote">"He who has never learned to obey cannot be a good commander"</p>
        </div>
      </article>
      <!-- end of single executive -->
      <!-- single executive -->
      <article class="executive" data-aos="fade-up" data-aos-duration="2000">
        <div class="executive-img-container">
          <img src="{% static 'main/img/osusami Rufus.jpg' %}" alt="">
        </div>
        <div class="executive-info">
          <h2 class="name">Osunsami Rufus</h2>
          <h3 class="position">Human resource director</h3>
          <p class="detail">200L, History Education, UI</p>
          <p class="quote">"Leaders often initiate their own learning"</p>
        </div>
      </article>
      <!-- end of single executive -->
      <!-- single executive -->
      <article class="executive" data-aos="fade-up" data-aos-duration="2000">
        <div class="executive-img-container">
          <img src="{% static 'main/img/kolawole aduragbemi.jpg' %}" alt="">
        </div>
        <div class="executive-info">
          <h2 class="name">Kolawole Aduragbemi</h2>
          <h3 class="position">Publicity director </h3>
          <p class="detail">200L Agronomy, UI</p>
          <p class="quote">"The task of leadership is not to put greatness into people, but to elicit it, for the greatness is there already"</p>
        </div>
      </article>
      <!-- end of single executive -->
      <!-- single executive -->
      <article class="executive" data-aos="fade-up" data-aos-duration="2000">
        <div class="executive-img-container">
          <img src="{% static 'main/img/olakunle david.jpg' %}" alt="">
        </div>
        <div class="executive-info">
          <h2 class="name">Olukunle David</h2>
          <h3 class="position">Editorial director</h3>
          <p class="detail">300L electrical and electronics engineering, UI</p>
          <p class="quote">"When the wind of change blew,some built walls while others built wind mills... Chinese proverb"</p>
        </div>
      </article>
      <!-- end of single executive -->
      <!-- single executive -->
      <article class="executive" data-aos="fade-up" data-aos-duration="2000">
        <div class="executive-img-container">
          <img src="{% static 'main/img/ogunbiyi hannah.jpg' %}" alt="">
        </div>
        <div class="executive-info">
          <h2 class="name">Ogunbiyi Hannah</h2>
          <h3 class="position">Graphics design and videography director</h3>
          <p class="detail">400L pharmacy, UI.</p>
          <p class="quote">"A leader is best when people barely know he exists, when his work done, his aim fulfilled, they will say: we did it ourselves"</p>
        </div>
      </article>
      <!-- end of single executive -->
      <!-- single executive -->
      <article class="executive" data-aos="fade-up" data-aos-duration="2000">
        <div class="executive-img-container">
          <img src="{% static 'main/img/alufa Oluwaferanmi.jpg' %}" alt="">
        </div>
        <div class="executive-info">
          <h2 class="name">Alufa Oluwaferanmi </h2>
          <h3 class="position">Grant Director</h3>
          <p class="detail">400L, Bachelor of Dental Surgery, UI</p>
          <p class="quote">"The spirit of a leader is cheerful, pleasant, optimistic, positive and open"</p>
        </div>
      </article>
      <!-- end of single executive -->
      <!-- single executive -->
      <article class="executive" data-aos="fade-up" data-aos-duration="2000">
        <div class="executive-img-container">
          <img src="{% static 'main/img/adelusi blessing.jpg' %}" alt="">
        </div>
        <div class="executive-info">
          <h2 class="name">Adelusi Blessing</h2>
          <h3 class="position">Content Director </h3>
          <p class="detail">200L, Agricultural Economics, UI</p>
          <p class="quote">"Finding solutions rather than comamplaining about a problem makes you a true leader"</p>
        </div>
      </article>
      <!-- end of single executive -->
      <!-- single executive -->
      <article class="executive" data-aos="fade-up" data-aos-duration="2000">
        <div class="executive-img-container">
          <img src="{% static 'main/img/wale.jpg' %}" alt="">
        </div>
        <div class="executive-info">
          <h2 class="name">Akinsote adewale</h2>
          <h3 class="position">Director of special duty</h3>
          <p class="detail">600L Bachelor of Dental Surgery</p>
          <!-- <p class="quote">"Finding solutions rather than comamplaining about a problem makes you a true leader"</p> -->
        </div>
      </article>
      <!-- end of single executive -->
    </div>
  </section>
{% endblock content %}

mainsite/src/main/templates/main/footer.html
{% load klatags %}
  <footer class="footer">
    <article class="footer-items">
      <div class="footer-contact">
        <div class="contact-us">
          <div class="footer-head">
            <h3>contact us</h3>
            <div class="footer-underline"></div>
          </div>
          <div class="contact-item">
            <i class="fas fa-address-book"></i>
            <p>E44, Alexander Brown Hall, Ibadan</p> 
          </div>
          <div class="contact-item">
            <i class="fas fa-phone"></i> 
            <p>+2348163482948</p>
          </div>
          <div class="contact-item">
            <i class="fas fa-envelope"></i>
            <a href="mailto:kingdomleads2021@gmail.com">kingdomleads2021@gmail.com</a>
          </div>
        </div>
        <div class="contact-form">
          {% contact_tag request %}
        </div>
        <div class="footer-menu">
          <div class="footer-head">
            <h3>Navigate the Site</h3>
            <div class="footer-underline"></div>
          </div>
          <ul class="footer-links">
          <li><a href="{% url 'main:home_page' %}">home</a></li>
          <li><a href="{% url 'main:about_page' %}">about us</a></li>
          <li><a href="{% url 'main:our_executives' %}">meet the executives</a></li>
          <li><a href="{% url 'main:programs_page' %}">our programs</a></li>
          <li><a href="{% url 'membership:application_form' %}">become a member</a></li>
          <li><a href="{% url 'main:donation_page' %}">donation/partnership</a></li>
          <li><a href="{% url 'blog:post_list' %}">blog</a></li>
        </ul>
        </div>
      </div>
    </article>

    <article class="footer-note">
      <div class="footer-icons">
          <div class="footer-icon">
            <a href="https://www.facebook.com/100076501002706"><i class="fab fa-facebook"></i></a>
          </div>
          <div class="footer-icon">
            <a href="https://twitter.com/kingdomleads"><i class="fab fa-twitter"></i></a>
          </div>
          <div class="footer-icon">
            <a href="https://www.instagram.com/kingdomleadsafrica"><i class="fab fa-instagram"></i></a>
          </div>
        </div>
        <div class="footer-right">
          <p>&copy; <span class="footer-date"></span> Kingdom Leads Africa. all right reserved</p>
        </div>
        <div class="designer">
          <p>site designed by <a href="https://twitter.com/Odeniyiojo">Heritage web dev</a></p>
        </div>
    </article>
  </footer>

mainsite/src/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
{% include "main/banner.html" %}
  <section class="vision section">
    <article class="vision-words">
      <div class="section-head">
          <h1>Our Vision</h1>
          <div class="section-underline"></div>
        </div>
        <div class="section-container">
          <div class="section-img section-info" data-aos="flip-up" data-aos-duration="2000">
            <img src="{% static 'main/img/binoculars-g4c21f6071_1920.jpg' %}" alt="">
          </div>
          <div class="section-word section-info">
            <p>To be the foremost international, pro leadership and non-profit organisation that transforms dependent youths into dependable leaders.</p>
            <a href="{% url 'main:about_page' %}" class="readmore-btn">Read More</a>
          </div>
        </div>
    </article>
  </section>
  <section class="mission-center section">
      <article class="mission-words">
        <div class="section-head">
          <h1>Our Mission</h1>
          <div class="section-underline"></div>
        </div>
        <div class="section-container" >
          <div class="section-img section-info" data-aos="fade-up" data-aos-duration="2000">
            <img src="{% static 'main/img/images (5).png' %}" alt="">
          </div>
          <div class="missions section-info">
                <!-- single mission -->
          <article class="mission show-text">
            <!-- mission title -->
            <div class="mission-title">
              <p>Our mission is </p>
              <button type="button" class="mission-btn">
                <span class="plus-icon">
                  <i class="far fa-plus-square"></i>
                </span>
                <span class="minus-icon">
                  <i class="far fa-minus-square"></i>
                </span>
              </button>
            </div>
            <!-- mission text -->
            <div class="mission-text">
              <ol>
                <li>To admit fresh tertiary students as fellows of the Freshire Campus Fellowship every year</li>
                <li>To admit senior secondary/high school students as fellows of the Highsphire Network of Promising Leaders every year</li>
                <li>To provide lifetime mentorship in all aspects of life for every HNPL and FCF fellows.</li>
                <p><a href="{% url 'main:about_page' %}" class="readmore-btn">Read More<a></p>
              </ol>
            </div>
          </article>
          <!-- end of single mission -->
          </div>
        </div>
    </article>
  </section>
  <section class="section events">
    <div class="section-head">
      <h1>Upcoming Events</h1>
      <div class="section-underline"></div>
    </div>
    <article class="events-center owl-carousel owl-theme">
    {% for event in events %}
    
      <!-- sigle event -->
      <div class="event-card">
        <div class="event-img-container">
          <img src="{{event.image.url}}" alt="" class="event-img">
        </div>
        <div class="event-info">
          <div class="event-title">
            <div class="">
              <i class="fas fa-calendar"></i>
            </div>
            <h1>{{event.title}}</h1>
          </div>
          <div class="event-details">
            <p>{{event.details|truncatewords:50}}</p>
          </div>
          <div class="event-date">
            <p>{{event.date}}</p>
          </div>
        </div>
      </div>
      <!-- end of single event -->
    {% endfor %}
    </article>
  </section>
  <section class="section gallery">
    <div class="section-head">
      <h1>our gallery</h1>
      <div class="section-underline"></div>
    </div>
    <br>
    <p>Click the picture to expand</p>
    <div class="gallery-container owl-carousel owl-theme">
      <!-- single gallery image -->
      <article class="gallery-item">
        <a href="{% static 'main/img/gallery 1.jpg' %}"><img src="{% static 'main/img/gallery 1.jpg' %}" alt=""></a>
      </article>
      <!-- end of single gallery img -->
      <!-- single gallery image -->
      <article class="gallery-item">
        <a href="{% static 'main/img/gallery 2.jpg' %}"><img src="{% static 'main/img/gallery 2.jpg' %}" alt=""></a>
      </article>
      <!-- end of single gallery img -->
      <!-- single gallery image -->
      <article class="gallery-item">
        <a href="{% static 'main/img/gallery 3.jpg' %}"><img src="{% static 'main/img/gallery 3.jpg' %}" alt=""></a>
      </article>
      <!-- end of single gallery img -->
      <!-- single gallery image -->
      <article class="gallery-item">
        <a href="{% static 'main/img/gallery 4.jpg' %}"><img src="{% static 'main/img/gallery 4.jpg' %}" alt=""></a>
      </article>
      <!-- end of single gallery img -->
      <!-- single gallery image -->
      <article class="gallery-item">
        <a href="{% static 'main/img/gallery 5.jpg' %}"><img src="{% static 'main/img/gallery 5.jpg' %}" alt=""></a>
      </article>
      <!-- end of single gallery img -->

    </div>
  </section>
  <section class="section events">
    <div class="section-head">
      <h1>Latest Posts</h1>
      <div class="section-underline"></div>
    </div>
    <article class="post-center-container owl-carousel owl-theme">
    {% for post in posts %}
    
      <!-- sigle event -->
      <div class="event-card">
        <div class="event-img-container">
          <a href="{{ post.get_absolute_url }}"><img src="{{post.image.url}}" alt="" class="event-img"></a>
        </div>
        <div class="event-info">
          <div class="event-title">
            <a href="{{ post.get_absolute_url }}"><h1>{{post.title}}</h1></a>
          </div>
          <div class="event-details">
            <p>{{post.content|safe|truncatewords:30}}</p>
            <a href="{{ post.get_absolute_url }}" class="readmore-btn">Read More</a>
          </div>
          <div class="event-date">
            <p>{{post.date}}</p>
          </div>
        </div>
      </div>
      <!-- end of single event -->
    {% endfor %}
    </article>
  </section>
{% endblock content %}

mainsite/src/main/templates/main/nav.html
{% load static %}
{% url 'main:home_page' as home %}
{% url 'main:our_executives' as executives %}
{% url 'main:about_page' as about %}
{% url 'main:programs_page' as programs %}
{% url 'main:donation_page' as donation %}
{% url 'membership:application_form' as membership %}
{% url 'blog:post_list' as blog %}
<header>
    <nav class="nav-bar">
      <div class="nav-top">
        <div class="nav-logo">
          <a href="{% url 'main:home_page' %}">
            <img src="{% static 'main/img/logo.png' %}" alt="my logo">
          </a>
        </div>
        <div class="nav-btn">
          <i class="fas fa-bars"></i>
        </div>
      </div>
      <div class="nav-contents">
        <ul class="nav-links">
          <li class="{% if request.path == home %} active-nav {% endif %}"><a href="{% url 'main:home_page' %}" class="nav-link">home</a></li>
          <li class="{% if request.path == about %} active-nav {% endif %}"><a href="{% url 'main:about_page' %}" class="nav-link">about us</a></li>
          <li class="{% if request.path == executives %} active-nav {% endif %}"><a href="{% url 'main:our_executives' %}" class="nav-link">meet the executives</a></li>
          <li class="{% if request.path == programs %} active-nav {% endif %}"><a href="{% url 'main:programs_page' %}" class="nav-link">our programs</a></li>
          <li class="{% if request.path == membership %} active-nav {% endif %}"><a href="{% url 'membership:application_form' %}" class="nav-link">become a member</a></li>
          <li class="{% if request.path == donation %} active-nav {% endif %}"><a href="{% url 'main:donation_page' %}" class="nav-link">donation/partnership</a></li>
          <li class="{% if request.path == blog %} active-nav {% endif %}"><a href="{% url 'blog:post_list' %}" class="nav-link">blog</a></li>

        </ul>
      </div>
    </nav>
  </header>

mainsite/src/main/templates/main/programs.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <section class="section programs">
    <div class="section-head">
      <h1>our programs</h1>
      <div class="section-underline"></div>
    </div>
    <div class="programs-info">
      <!-- single mission -->
          <article class="mission show-text">
            <!-- mission title -->
            <div class="mission-title">
              <p>High school students</p>
              <button type="button" class="mission-btn">
                <span class="plus-icon">
                  <i class="far fa-plus-square"></i>
                </span>
                <span class="minus-icon">
                  <i class="far fa-minus-square"></i>
                </span>
              </button>
            </div>
            <!-- mission text -->
            <div class="mission-text">
              <p>Annual Kingdom Leads Africa Fellowship for High School Students</p>
            </div>
          </article>
          <!-- end of single mission -->
      <!-- single mission -->
          <article class="mission">
            <!-- mission title -->
            <div class="mission-title">
              <p>Fresh Tertiary Students</p>
              <button type="button" class="mission-btn">
                <span class="plus-icon">
                  <i class="far fa-plus-square"></i>
                </span>
                <span class="minus-icon">
                  <i class="far fa-minus-square"></i>
                </span>
              </button>
            </div>
            <!-- mission text -->
            <div class="mission-text">
              <p>Annual Kingdom Leads Africa Fellowship for Fresh Tertiary School Students</p>
            </div>
          </article>
          <!-- end of single mission -->
      <!-- single mission -->
          <article class="mission">
            <!-- mission title -->
            <div class="mission-title">
              <p>Mentorship</p>
              <button type="button" class="mission-btn">
                <span class="plus-icon">
                  <i class="far fa-plus-square"></i>
                </span>
                <span class="minus-icon">
                  <i class="far fa-minus-square"></i>
                </span>
              </button>
            </div>
            <!-- mission text -->
            <div class="mission-text">
              <p>Lifetime mentorship for fellows of the KLAF</p>
            </div>
          </article>
          <!-- end of single mission -->
    </div>
  </section>
{% endblock content %}